version: "3.9"

services:
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: YOUR_IP:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://YOUR_IP:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
